name: Build and Deploy

on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.tdkottke.com
          username: github-deployment
          password: ${{ secrets.DOCKER_CLIENT_SECRET }}

      - name: Build Docker Image
        run: docker build -t registry.tdkottke.com/tkottke90/ai-assistant-api:${{github.ref_name}} .

      - name: Push To Registry
        run: docker push registry.tdkottke.com/tkottke90/ai-assistant-api:${{github.ref_name}}