name: Build and Deploy

on:
  workflow-dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.tdkottke.com

    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: github-deployment
          password: ${{ secrets.DOCKER_CLIENT_SECRET }}

      - name: Build Docker Image
        env:
          IMAGE: ${{ env.REGISTRY }}/tkottke90/ai-assistant-api:${{github.ref_name}}
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push To Registry
        env:
          IMAGE: ${{ env.REGISTRY }}/tkottke90/ai-assistant-api:${{github.ref_name}}
        run: docker push ${{ env.IMAGE }}
